=== AlvaroMar1/sadasdas/XSD/repaso/instituto.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="instituto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="modulos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="modulo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"></xs:element>
                                        <xs:element name="curso" type="xs:string"></xs:element>
                                        <xs:element name="horasSemanales" type="xs:integer"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="identificador" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="aulas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="aula">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tipo" type="xs:string"></xs:element>
                                        <xs:element name="capacidad" type="xs:integer"></xs:element>
                                        <xs:element name="fecha_revision" type="xs:string"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="identificador" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AlvaroMar1/sadasdas/XSD/repaso/instituto.xml
<?xml version="1.0" encoding="UTF-8"?>
<instituto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="instituto.xsd">

    <modulos>
        <modulo identificador="LMSGI">
            <nombre>Lenguaje de Marcas</nombre>
            <curso>1º</curso>
            <horasSemanales>5</horasSemanales>
        </modulo>
    </modulos>

    <aulas>
        <aula identificador="A101">
            <tipo>Teoria</tipo>
            <capacidad>30</capacidad>
            <fecha_revision>2025-08-15</fecha_revision>
        </aula>
    </aulas>
</instituto>
